# Generated by Django 5.0.2 on 2024-03-14 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='date',
        ),
        migrations.AddField(
            model_name='reservation',
            name='time',
            field=models.TimeField(default='17:00'),
        ),
        migrations.AddField(
            model_name='table',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
