# Generated by Django 5.0.2 on 2024-03-25 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_alter_reservation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='notes',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
